### ISSUE TITLE
Dependencies are not available anymore

### ISSUE THREAD

**Issue by sebinefrancis** [linganesan/3D-diff#1]
Hello,
"Just install https://github.com/revarbat/pycsg and it dependencies :)" This dependency is not available. But I found anothert repo of this : https://github.com/timknip/pycsg . But these codes doesnot have a function `readSTL()`. 

Can someone share the original pycsg dependency codes which contain `readSTL()` function in it,  or a code which can make this repo working. ?

Thanks

**Comment by mani-nesan** [comment]
Hey!
Thanks for the heads up, this is just fun project I did yearssss back 😄 

Seems that project was removed by the author, though she/he made a pull request to the original repo!
[https://github.com/timknip/pycsg/pull/9](https://github.com/timknip/pycsg/pull/9)
which is still not been merged, maybe the project is inactive.

So I made a fork and merged change as a patch!

[https://github.com/mani-nesan/pycsg](https://github.com/mani-nesan/pycsg)

Hope this has those STL functions!

Cheers 🥂
